---
# Since version >4.1 some other dependencies are required.
- name: INSTALL DEPENDENCIES
  package:
    name: '{{ item.name | default(item) }}'
    state: '{{ item.state | default(omit) }}'
  loop: '{{ motion_dependencies }}'

- name: INSTALL APPLICATION
  package:
    name: '{{ item.name | default(item) }}'
    state: '{{ item.state | default(omit) }}'
  loop: '{{ motion_packages }}'

  # Create the output/target_dirs for the files as specified.
- name: MANAGE OUTPUT DIRECTORIES
  file:
    state: directory
    path: "{{ item['target_dir'] }}"
  loop: '{{ motion_config }}'
  when:
    - (item['state'] is defined and item['state'] not in ('absent') and item['target_dir'] is defined) or
      (item['state'] is undefined and item['target_dir'] is defined)
...
